[project]
name = "pythonproject"
version = "0.1.0"
description = "AtoZ Client"
channels = ["conda-forge"]
platforms = ["win-64", "osx-64", "osx-arm64", "linux-64"]

[dependencies]
python = ">=3.11,<3.13"
watchdog = "*"
tomli = "*"
dacite = "*"
selenium = "*"
webdriver-manager = "*"
geckodriver = "*"
tzdata = "*"
httpx = "*"
h2 = "*"
requests = "*"
parsedatetime = "*"
o365 = "*"
python-dotenv = "*"

[tasks]
# Run the app (pass CLI args after `--`)
app = "python main.py"
